#!/usr/bin/env python3
"""
Export the deterministic detection layer to JavaScript for the static demo.

Reads the real PIIPattern definitions from preserve.patterns (so the browser
demo can never drift from the library) and emits docs/assets/patterns.js:

    window.PRESERVE_PATTERNS = [ { name, source, flags, group, sensitivity,
                                   replacement_type, description }, ... ];

Only Layer 2a (regex) metadata is exported. The checksum validators (Layer 2c)
are hand-ported in docs/assets/app.js and keyed by pattern name; this script
prints which pattern names have validators so the two stay in sync.

Usage:
    python scripts/export_patterns.py
"""

from __future__ import annotations

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from preserve.patterns import ALL_PATTERNS
from preserve.validators import VALIDATORS
from preserve import context as ctx

ASSETS = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "docs", "assets",
)
OUT = os.path.join(ASSETS, "patterns.js")
OUT_CTX = os.path.join(ASSETS, "context.js")


def _flags(rx) -> str:
    return "i" if (rx.flags & re.IGNORECASE) else ""


def export_context() -> None:
    """Emit context-scoring data (Layer 2d) ported from preserve/context.py."""
    boosters = {
        t: [[rx.pattern, _flags(rx), boost] for rx, boost in pairs]
        for t, pairs in ctx.CONTEXT_BOOSTERS.items()
    }
    generic = [[rx.pattern, _flags(rx), boost] for rx, boost in ctx.GENERIC_BOOSTERS]
    reducers = [[rx.pattern, _flags(rx), red] for rx, red in ctx.CONTEXT_REDUCERS]
    data = {
        "window": ctx.CONTEXT_WINDOW,
        "boosters": boosters,
        "generic": generic,
        "reducers": reducers,
    }
    with open(OUT_CTX, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by scripts/export_patterns.py — do not edit by hand.\n")
        f.write("// Source of truth: preserve/context.py\n")
        f.write("window.PRESERVE_CONTEXT = ")
        f.write(json.dumps(data, indent=2, ensure_ascii=False))
        f.write(";\n")
    print(f"Wrote context scoring -> {OUT_CTX}")


# Scoped inline flags like "(?i:...)" are valid in Python but not in JS regex,
# and can't be globalized without changing semantics (e.g. case-sensitive name
# extraction). Such patterns are skipped from the browser demo.
SCOPED_INLINE_FLAG = re.compile(r"\(\?[a-zA-Z]+:")


def export() -> None:
    rows = []
    skipped = []
    for p in ALL_PATTERNS:
        if SCOPED_INLINE_FLAG.search(p.regex.pattern):
            skipped.append(p.name)
            continue
        rows.append({
            "name": p.name,
            "source": p.regex.pattern,
            "flags": _flags(p.regex),
            "group": 1 if p.regex.groups >= 1 else 0,  # extract group 1 if present
            "sensitivity": p.min_sensitivity.value,
            "replacement_type": p.replacement_type,
            "description": p.description,
            "has_validator": p.name in VALIDATORS,
        })

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    body = json.dumps(rows, indent=2, ensure_ascii=False)
    header = (
        "// AUTO-GENERATED by scripts/export_patterns.py — do not edit by hand.\n"
        "// Source of truth: preserve/patterns.py\n"
        f"// {len(rows)} patterns exported.\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("window.PRESERVE_PATTERNS = ")
        f.write(body)
        f.write(";\n")

    print(f"Wrote {len(rows)} patterns -> {OUT}")
    if skipped:
        print(f"Skipped {len(skipped)} pattern(s) with JS-incompatible scoped inline flags: {', '.join(skipped)}")
    validated = sorted(p["name"] for p in rows if p["has_validator"])
    print(f"Patterns with checksum validators ({len(validated)}): {', '.join(validated)}")


if __name__ == "__main__":
    export()
    export_context()
