#!/usr/bin/env python3
"""
Export the deterministic detection layer to JavaScript for the static demo.

Reads the real PIIPattern definitions from preserve.patterns (so the browser
demo can never drift from the library) and emits docs/assets/patterns.js:

    window.PRESERVE_PATTERNS = [ { name, source, flags, group, sensitivity,
                                   replacement_type, description }, ... ];

Only Layer 2a (regex) metadata is exported. The checksum validators (Layer 2c)
are hand-ported in docs/assets/app.js and keyed by pattern name; this script
prints which pattern names have validators so the two stay in sync.

Usage:
    python scripts/export_patterns.py
"""

from __future__ import annotations

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from preserve.patterns import ALL_PATTERNS
from preserve.validators import VALIDATORS
from preserve import context as ctx

ASSETS = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "docs", "assets",
)
OUT = os.path.join(ASSETS, "patterns.js")
OUT_CTX = os.path.join(ASSETS, "context.js")


def _flags(rx) -> str:
    return "i" if (rx.flags & re.IGNORECASE) else ""


def export_context() -> None:
    """Emit context-scoring data (Layer 2d) ported from preserve/context.py."""
    boosters = {
        t: [[rx.pattern, _flags(rx), boost] for rx, boost in pairs]
        for t, pairs in ctx.CONTEXT_BOOSTERS.items()
    }
    generic = [[rx.pattern, _flags(rx), boost] for rx, boost in ctx.GENERIC_BOOSTERS]
    reducers = [[rx.pattern, _flags(rx), red] for rx, red in ctx.CONTEXT_REDUCERS]
    data = {
        "window": ctx.CONTEXT_WINDOW,
        "boosters": boosters,
        "generic": generic,
        "reducers": reducers,
    }
    with open(OUT_CTX, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by scripts/export_patterns.py — do not edit by hand.\n")
        f.write("// Source of truth: preserve/context.py\n")
        f.write("window.PRESERVE_CONTEXT = ")
        f.write(json.dumps(data, indent=2, ensure_ascii=False))
        f.write(";\n")
    print(f"Wrote context scoring -> {OUT_CTX}")


# JS regex has no scoped inline flags like "(?i:...)". We rewrite such a group
# into a case-insensitive form by "case-classing" its letters (patient ->
# [pP][aA][tT][iI][eE][nN][tT]), leaving any case-sensitive capture group that
# follows (e.g. the [A-Z][a-z]+ name shape) untouched.
def _case_class(text: str) -> str:
    out = []
    for ch in text:
        if ch.isascii() and ch.isalpha():
            out.append(f"[{ch.lower()}{ch.upper()}]")
        else:
            out.append(ch)
    return "".join(out)


def rewrite_inline_flags(source: str) -> str:
    out, i, n = [], 0, len(source)
    while i < n:
        if source.startswith("(?i:", i):
            depth, j, in_class = 1, i + 4, False
            inner_start = j
            while j < n:
                c = source[j]
                if c == "\\":
                    j += 2
                    continue
                if in_class:
                    if c == "]":
                        in_class = False
                elif c == "[":
                    in_class = True
                elif c == "(":
                    depth += 1
                elif c == ")":
                    depth -= 1
                    if depth == 0:
                        break
                j += 1
            # Wrap in a non-capturing group to preserve the original grouping
            # (otherwise a top-level "a|b" alternation would no longer be bounded).
            out.append("(?:" + _case_class(source[inner_start:j]) + ")")
            i = j + 1  # skip the matching ')'
        else:
            out.append(source[i])
            i += 1
    return "".join(out)


def export() -> None:
    rows = []
    for p in ALL_PATTERNS:
        rows.append({
            "name": p.name,
            "source": rewrite_inline_flags(p.regex.pattern),
            "flags": _flags(p.regex),
            "group": 1 if p.regex.groups >= 1 else 0,  # extract group 1 if present
            "sensitivity": p.min_sensitivity.value,
            "replacement_type": p.replacement_type,
            "description": p.description,
            "has_validator": p.name in VALIDATORS,
        })

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    body = json.dumps(rows, indent=2, ensure_ascii=False)
    header = (
        "// AUTO-GENERATED by scripts/export_patterns.py — do not edit by hand.\n"
        "// Source of truth: preserve/patterns.py\n"
        f"// {len(rows)} patterns exported.\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(header)
        f.write("window.PRESERVE_PATTERNS = ")
        f.write(body)
        f.write(";\n")

    print(f"Wrote {len(rows)} patterns -> {OUT}")
    validated = sorted(p["name"] for p in rows if p["has_validator"])
    print(f"Patterns with checksum validators ({len(validated)}): {', '.join(validated)}")


if __name__ == "__main__":
    export()
    export_context()
