#!/usr/bin/env python3
"""
Export a compact name gazetteer to JavaScript for the static browser demo.

The full Python name scorer (preserve/name_scorer.py, Layer 2h) loads the entire
`names-dataset` (~150 MB RAM) plus `wordfreq`. That is far too heavy to ship to a
browser. This script distills the same two sources into a small bundle so the demo
can detect bare personal names across the major countries without any server:

    window.PRESERVE_NAMES = {
        first:  [ ...lowercased common first names... ],
        last:   [ ...lowercased common last names... ],
        common: [ ...most frequent English words (used to penalise word-names)... ],
        countries: <int>,
    };

The JS port in docs/assets/app.js mirrors the scoring logic of name_scorer.py,
using membership in `common` as a stand-in for the wordfreq penalty.

Run after changing the country list or thresholds:
    python scripts/export_names.py
"""

from __future__ import annotations

import json
import os
import re
import sys

ASSETS = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "docs", "assets",
)
OUT = os.path.join(ASSETS, "names.js")

# Major countries spanning the Americas, Europe, Africa, the Middle East,
# South Asia, and East/Southeast Asia. Codes not present in names-dataset are
# skipped automatically (reported at the end).
MAJOR_COUNTRIES = [
    # Anglophone
    "US", "GB", "CA", "AU", "IE", "NZ",
    # Western / Northern Europe
    "FR", "DE", "ES", "IT", "PT", "NL", "BE", "CH", "AT",
    "SE", "NO", "DK", "FI",
    # Central / Eastern Europe
    "PL", "RU", "UA", "CZ", "GR", "TR", "RO", "HU", "RS",
    # Latin America
    "BR", "MX", "AR", "CO", "CL", "PE",
    # Africa
    "NG", "ZA", "KE", "EG", "ET", "GH", "MA",
    # Middle East
    "SA", "IL", "IR", "AE",
    # South / Southeast / East Asia
    "IN", "PK", "BD", "ID", "VN", "TH", "PH", "CN", "JP", "KR",
]

# How many top names per country (per gender for first names) to pull.
TOP_PER_COUNTRY = 150
# Size of the common-English-word list used to suppress word-names ("Will", "May").
COMMON_WORDS = 2500
# Minimum token length kept in the gazetteer (drops noisy 1-2 char fragments).
MIN_LEN = 3

_TOKEN_RE = re.compile(r"^[\w'\-]{%d,}$" % MIN_LEN, re.UNICODE)


def _clean(name: str) -> str | None:
    tok = name.strip().lower()
    if not _TOKEN_RE.match(tok) or tok.isdigit():
        return None
    return tok


def _collect(values, sink: set[str]) -> None:
    """Flatten the {gender: [..]} or [..] shapes names-dataset returns."""
    if isinstance(values, dict):
        for v in values.values():
            _collect(v, sink)
    elif isinstance(values, list):
        for v in values:
            c = _clean(v)
            if c:
                sink.add(c)


def main() -> int:
    try:
        from names_dataset import NameDataset
        from wordfreq import top_n_list
    except ImportError as e:
        print(f"error: {e}. Install with: pip install names-dataset wordfreq", file=sys.stderr)
        return 1

    nd = NameDataset()
    first: set[str] = set()
    last: set[str] = set()
    ok, skipped = [], []

    for code in MAJOR_COUNTRIES:
        try:
            f = nd.get_top_names(n=TOP_PER_COUNTRY, use_first_names=True, country_alpha2=code)
            l = nd.get_top_names(n=TOP_PER_COUNTRY, use_first_names=False, country_alpha2=code)
            _collect(f.get(code), first)
            _collect(l.get(code), last)
            ok.append(code)
        except Exception:
            skipped.append(code)

    common = {w.lower() for w in top_n_list("en", COMMON_WORDS)}

    payload = {
        "first": sorted(first),
        "last": sorted(last),
        "common": sorted(common),
        "countries": len(ok),
    }

    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    header = (
        "// AUTO-GENERATED by scripts/export_names.py — do not edit by hand.\n"
        "// Compact name gazetteer distilled from names-dataset + wordfreq so the\n"
        "// browser demo can detect bare international names without a server.\n"
    )
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(header)
        fh.write("window.PRESERVE_NAMES = ")
        fh.write(body)
        fh.write(";\n")

    size_kb = os.path.getsize(OUT) / 1024
    print(f"wrote {OUT}")
    print(f"  countries: {len(ok)} ok, {len(skipped)} skipped ({', '.join(skipped) or 'none'})")
    print(f"  first names: {len(first)}, last names: {len(last)}, common words: {len(common)}")
    print(f"  file size: {size_kb:.0f} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
